<!-- TMX 1.4b DTD - Translation Memory eXchange format
     Reconstructed from the LISA OSCAR specification (2005-04-26)
     for local validation use.
-->

<!ELEMENT tmx (header, body)>
<!ATTLIST tmx
  version CDATA #REQUIRED
>

<!ELEMENT header (note*, prop*, ude*)>
<!ATTLIST header
  creationtool         CDATA  #REQUIRED
  creationtoolversion  CDATA  #REQUIRED
  segtype              (block|paragraph|sentence|phrase)  #REQUIRED
  o-tmf                CDATA  #REQUIRED
  adminlang            CDATA  #REQUIRED
  srclang              CDATA  #REQUIRED
  datatype             CDATA  #REQUIRED
  o-encoding           CDATA  #IMPLIED
  creationdate         CDATA  #IMPLIED
  creationid           CDATA  #IMPLIED
  changedate           CDATA  #IMPLIED
  changeid             CDATA  #IMPLIED
>

<!ELEMENT body (tu*)>

<!ELEMENT tu (note*, prop*, tuv+)>
<!ATTLIST tu
  tuid                 CDATA  #IMPLIED
  o-encoding           CDATA  #IMPLIED
  datatype             CDATA  #IMPLIED
  usagecount           CDATA  #IMPLIED
  lastusagedate        CDATA  #IMPLIED
  creationtool         CDATA  #IMPLIED
  creationtoolversion  CDATA  #IMPLIED
  creationdate         CDATA  #IMPLIED
  creationid           CDATA  #IMPLIED
  changedate           CDATA  #IMPLIED
  segtype              (block|paragraph|sentence|phrase)  #IMPLIED
  changeid             CDATA  #IMPLIED
  o-tmf                CDATA  #IMPLIED
  srclang              CDATA  #IMPLIED
>

<!ELEMENT tuv (note*, prop*, seg)>
<!ATTLIST tuv
  xml:lang             CDATA  #REQUIRED
  o-encoding           CDATA  #IMPLIED
  datatype             CDATA  #IMPLIED
  usagecount           CDATA  #IMPLIED
  lastusagedate        CDATA  #IMPLIED
  creationtool         CDATA  #IMPLIED
  creationtoolversion  CDATA  #IMPLIED
  creationdate         CDATA  #IMPLIED
  creationid           CDATA  #IMPLIED
  changedate           CDATA  #IMPLIED
  o-tmf                CDATA  #IMPLIED
  changeid             CDATA  #IMPLIED
>

<!ELEMENT seg (#PCDATA | bpt | ept | it | ph | hi | ut )*>

<!ELEMENT bpt (#PCDATA | sub )*>
<!ATTLIST bpt
  i              CDATA  #REQUIRED
  x              CDATA  #IMPLIED
  type           CDATA  #IMPLIED
>

<!ELEMENT ept (#PCDATA | sub )*>
<!ATTLIST ept
  i              CDATA  #REQUIRED
>

<!ELEMENT it (#PCDATA | sub )*>
<!ATTLIST it
  pos            (begin|end)  #REQUIRED
  x              CDATA        #IMPLIED
  type           CDATA        #IMPLIED
>

<!ELEMENT ph (#PCDATA | sub )*>
<!ATTLIST ph
  x              CDATA  #IMPLIED
  type           CDATA  #IMPLIED
  assoc          (p|f|b)  #IMPLIED
>

<!ELEMENT hi (#PCDATA | bpt | ept | it | ph | hi | ut )*>
<!ATTLIST hi
  x              CDATA  #IMPLIED
  type           CDATA  #IMPLIED
>

<!ELEMENT ut (#PCDATA | sub )*>
<!ATTLIST ut
  x              CDATA  #IMPLIED
>

<!ELEMENT sub (#PCDATA | bpt | ept | it | ph | hi | ut )*>
<!ATTLIST sub
  type           CDATA  #IMPLIED
  datatype       CDATA  #IMPLIED
>

<!ELEMENT prop (#PCDATA)>
<!ATTLIST prop
  type           CDATA  #REQUIRED
  xml:lang       CDATA  #IMPLIED
  o-encoding     CDATA  #IMPLIED
>

<!ELEMENT note (#PCDATA)>
<!ATTLIST note
  xml:lang       CDATA  #IMPLIED
  o-encoding     CDATA  #IMPLIED
>

<!ELEMENT ude (map+)>
<!ATTLIST ude
  name           CDATA  #REQUIRED
  base           CDATA  #IMPLIED
>

<!ELEMENT map EMPTY>
<!ATTLIST map
  unicode        CDATA  #REQUIRED
  code           CDATA  #IMPLIED
  ent            CDATA  #IMPLIED
  subst          CDATA  #IMPLIED
>
